version: '3.8'

services:
  web-page:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: unless-stopped
    image: web-page:latest
    container_name: cthulhu-web-page
    init: true
    ports:
      - "8000:8000"
    expose:
      - 8000
    volumes:
      - ./web/logs:/app/logs
      - ./web/data:/app/data
      - ./web/static:/app/static
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_HOST=mongo
      - UVICON_HOST=0.0.0.0
    env_file:
      - .env
    entrypoint: ["uvicorn"]
    command: ["main:app", "--host=0.0.0.0", "--port=8000"]
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"

  web-etl:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: unless-stopped
    image: web-etl:latest
    container_name: cthulhu-web-etl
    init: true
    volumes:
      - ./web/logs:/app/logs
      - ./web/data:/app/data
      - ./web/static:/app/static
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_HOST=mongo
    env_file:
      - .env
    entrypoint: ["python"]
    command: ["-m", "main"]
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"

  db-etl:
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: unless-stopped
    image: db-etl:latest
    container_name: cthulhu-db-etl
    init: true
    volumes:
      - ./db/logs:/app/logs
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_HOST=mongo
    env_file:
      - .env
    entrypoint: ["python"]
    command: ["-m", "main"]
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"

  mongo:
    restart: unless-stopped
    image: mongo:latest
    container_name: cthulhu-mongo
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - ./db/data/mongo_storage:/data/db
      - ./db/logs/mongo_log:/var/log/mongodb
      - ./db/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_HOST=0.0.0.0
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"

  qdrant:
    restart: unless-stopped
    image: qdrant/qdrant:latest
    container_name: cthulhu-qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
    volumes:
      - ./db/data/qdrant_storage:/qdrant/storage
    environment:
      - PUID=1000
      - PGID=1000
      - QDRANT__LOG_LEVEL=INFO
      - QDRANT__SERVICE__HTTP_PORT=6333
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"

networks:
  default:
    name: cthulhu-net
    driver: bridge
